[features]
seeds = false
[programs.devnet]
zircon_docs = "FoyfSugJpPAzywE2yTVJVDyUmVzQ3rVSy3UoaeYhgia6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vin_gitonga/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
